name: widgetbook_workspace
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  auravibes_ui:
    path: ../packages/auravibes_ui
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.9.0

dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.16.0

flutter:
  uses-material-design: true
