name: Flutter Test CI

on:
  push:
    branches:
      - main
      - dev
      - stage
  pull_request:
    branches:
      - main
      - dev
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v5

      - name: ğŸ”§ Setup FVM
        uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config-action

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub-:os:-:channel:-:version:-:arch:-${{ hashFiles('pubspec.lock') }}" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
      - uses: bluefireteam/melos-action@v3
        with:
          enforce-lockfile: true
          run-bootstrap: true

      - name: âœ¨ Check Formatting
        run: dart format --line-length 80 --set-exit-if-changed .

      - name: ğŸ•µï¸â€â™‚ï¸ Analyze
        run: flutter analyze .

      - name: ğŸ§ª Run Tests
        run: flutter test .

      - name: ğŸ“¦ Dependency Validation
        run: dart run dependency_validator

      - name: ğŸ“ Import Sorting
        run: dart run import_sorter:main --exit-if-changed
