name: Flutter Test CI

on:
  push:
    branches:
      - main
      - dev
      - stage
  pull_request:
    branches:
      - main
      - dev
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“š Git Checkout
        uses: actions/checkout@v5

      - name: ğŸ”§ Setup FVM
        uses: kuhnroyal/flutter-fvm-config-action/config@v3
        id: fvm-config-action

      - name: ğŸ¦ Setup Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true

      - name: Conditionally run melos bootstrap
        if: steps.flutter-action.outputs.PUB-CACHE-HIT != 'true'
        run: melos bootstrap

      - name: âœ¨ Check Formatting
        run: dart format --line-length 80 --set-exit-if-changed .

      - name: ğŸ•µï¸â€â™‚ï¸ Analyze
        run: flutter analyze .

      - name: ğŸ§ª Run Tests
        run: flutter test .

      - name: ğŸ“¦ Dependency Validation
        run: dart run dependency_validator

      - name: ğŸ“ Import Sorting
        run: dart run import_sorter:main --exit-if-changed
